[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "bioclients"
description = "Clients and tools for online biomedical resources, usually via REST APIs."
authors = [
	{name = "Jeremy J Yang", email = "jeremyjyang@gmail.com"},
]
version = "0.2.34"
requires-python = ">= 3.10"
dependencies = [
	"pandas",
	"requests",
	"pyyaml",
	"click",
	"tqdm",
	"numpy",
	"pyquery",
	"sqlalchemy",
	"psycopg2",
]
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
]

[project.urls]
HomePage = "https://github.com/jeremyjyang/bioclients"
